sudo: required

services:
    - docker

language: python

matrix:
    include:
        - env: BASE_IMAGE="fedora_python3"
          before_install:
            - docker build --no-cache --tag ssg_$BASE_IMAGE:latest -f Dockerfiles/$BASE_IMAGE .
          script:
            - docker run ssg_$BASE_IMAGE:latest
        - env: BASE_IMAGE="ubuntu"
          before_install:
            - docker build --no-cache --tag ssg_$BASE_IMAGE:latest -f Dockerfiles/$BASE_IMAGE .
          script:
            - docker run ssg_$BASE_IMAGE:latest
        - env: BASE_IMAGE="fedora_python2"
          before_install:
            - docker build --no-cache --tag ssg_$BASE_IMAGE:latest -f Dockerfiles/$BASE_IMAGE .
          script:
            - docker run ssg_$BASE_IMAGE:latest
        - env: BASE_IMAGE="centos8"
          before_install:
            - docker build --no-cache --tag ssg_$BASE_IMAGE:latest -f Dockerfiles/$BASE_IMAGE .
          script:
            - docker run ssg_$BASE_IMAGE:latest
        - env: BASE_IMAGE="fedora_python3"
          arch:
            - ppc64le
          before_install:
            - docker build --no-cache --tag ssg_$BASE_IMAGE:latest -f Dockerfiles/$BASE_IMAGE .
          script:
            - docker run ssg_$BASE_IMAGE:latest
        - env: BASE_IMAGE="ubuntu"
          arch:
            - ppc64le
          before_install:
            - docker build --no-cache --tag ssg_$BASE_IMAGE:latest -f Dockerfiles/$BASE_IMAGE .
          script:
            - docker run ssg_$BASE_IMAGE:latest
        - env: BASE_IMAGE="fedora_python2"
          arch:
            - ppc64le
          before_install:
            - docker build --no-cache --tag ssg_$BASE_IMAGE:latest -f Dockerfiles/$BASE_IMAGE .
          script:
            - docker run ssg_$BASE_IMAGE:latest
        - env: BASE_IMAGE="centos8"
          arch:
            - ppc64le
          before_install:
            - docker build --no-cache --tag ssg_$BASE_IMAGE:latest -f Dockerfiles/$BASE_IMAGE .
          script:
            - docker run ssg_$BASE_IMAGE:latest

